export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',

  ADMIN_PREFIX: '/admin',
  AGENCY_PREFIX: '/agency',
  CAREGIVER_PREFIX: '/caregiver',
  CLIENT_PREFIX: '/client',

  // Super admin routes
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_AGENCIES: '/admin/agencies',
  ADMIN_INVITATIONS: '/admin/invitations',
  ADMIN_CREATE_INVITATION: '/admin/invitations/create',
  ADMIN_SUBSCRIPTION_PLANS: '/admin/subscription-plans',
  ADMIN_USERS: '/admin/users',
  ADMIN_TEAM: '/admin/team',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_CLIENTS: '/admin/clients',
  ADMIN_CAREGIVERS: '/admin/caregivers',
  ADMIN_SCHEDULES: '/admin/schedules',
  ADMIN_EVV_COMPLIANCE: '/admin/evv-compliance',
  ADMIN_MEDICAID: '/admin/medicaid',
  ADMIN_BILLING_CLAIMS: '/admin/billing-claims',
  ADMIN_FINANCE: '/admin/finance',
  ADMIN_PAYMENTS: '/admin/payments',
  ADMIN_SOCIAL: '/admin/social',
  ADMIN_MARKETING: '/admin/marketing',
  ADMIN_REFERRALS: '/admin/referrals',
  ADMIN_CRM: '/admin/crm',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_AUDIT_LOGS: '/admin/audit-logs',
  ADMIN_INTEGRATIONS: '/admin/integrations',
  ADMIN_SUPPORT: '/admin/support',
  ADMIN_CONTENT: '/admin/content',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_PROFILE: '/admin/profile',

  // Agency owner / HR portal
  AGENCY_DASHBOARD: '/agency/dashboard',
  AGENCY_CLIENTS: '/agency/clients',
  AGENCY_CLIENTS_INTAKE: '/agency/clients/intake',
  AGENCY_CLIENTS_EDIT: '/agency/clients/:id/edit',
  AGENCY_INSURANCE_INTAKE: '/agency/insurance-intake',
  AGENCY_INSURANCE_INTAKE_CREATE: '/agency/insurance-intake/new',
  AGENCY_INSURANCE_INTAKE_EDIT: '/agency/insurance-intake/:id/edit',
  AGENCY_INSURANCE_INTAKE_PRINT: '/agency/insurance-intake/:id/print',
  AGENCY_INSURANCE_INTAKE_PRINT_DRAFT: '/agency/insurance-intake/draft/print',
  AGENCY_LEADS: '/agency/leads',
  AGENCY_LEADS_CREATE: '/agency/leads/new',
  AGENCY_LEADS_DETAIL: '/agency/leads/:id',
  AGENCY_LEADS_EDIT: '/agency/leads/:id/edit',
  AGENCY_ASSESSMENTS: '/agency/assessments',
  AGENCY_ASSESSMENTS_CREATE: '/agency/assessments/new',
  AGENCY_ASSESSMENTS_EDIT: '/agency/assessments/:id/edit',
  AGENCY_ASSESSMENTS_PRINT: '/agency/assessments/:id/print',
  AGENCY_ASSESSMENTS_PRINT_DRAFT: '/agency/assessments/draft/print',
  AGENCY_CARE_PLANS: '/agency/care-plans',
  AGENCY_CARE_PLANS_CREATE: '/agency/care-plans/create',
  AGENCY_CARE_PLANS_EDIT: '/agency/care-plans/:id/edit',
  AGENCY_CARE_PLANS_VERSIONS: '/agency/care-plans/:id/versions',
  AGENCY_CARE_PLANS_VERSION_PRINT: '/agency/care-plans/:id/versions/:historyId/print',
  AGENCY_CARE_PLANS_PRINT: '/agency/care-plans/:id/print',
  AGENCY_CARE_PLANS_PRINT_DRAFT: '/agency/care-plans/draft/print',
  AGENCY_SERVICE_NOTES: '/agency/service-notes',
  AGENCY_MEDICATIONS: '/agency/medications',
  AGENCY_EMAR: '/agency/emar',
  AGENCY_SCHEDULE: '/agency/schedule',
  AGENCY_VISIT_CALENDAR: '/agency/visit-calendar',
  AGENCY_SHIFT_MANAGEMENT: '/agency/shift-management',
  AGENCY_TIME_ATTENDANCE: '/agency/time-attendance',
  AGENCY_EVV_DASHBOARD: '/agency/evv/dashboard',
  AGENCY_EVV_LOGS: '/agency/evv/logs',
  AGENCY_EVV_EXCEPTIONS: '/agency/evv/exceptions',
  AGENCY_EVV_UNVERIFIED: '/agency/evv/unverified',
  AGENCY_EVV_ENROLLMENTS: '/agency/evv/enrollments',
  AGENCY_EVV_ENROLLMENTS_REVIEW: '/agency/evv/enrollments/:id/review',
  AGENCY_EVV_ENROLLMENT_PRINT: '/agency/evv/enrollments/:id/print',
  AGENCY_EVV_SETTINGS: '/agency/evv/settings',
  AGENCY_CAREGIVERS: '/agency/caregivers',
  AGENCY_HOLIDAYS: '/agency/holidays',
  AGENCY_LEAVE_POLICY: '/agency/leave-policy',
  AGENCY_LEAVE_REQUESTS: '/agency/leave-requests',
  AGENCY_CAREGIVER_MATCHING: '/agency/caregiver-matching',
  AGENCY_TASKS: '/agency/tasks',
  AGENCY_INCIDENTS: '/agency/incidents',
  AGENCY_REPORTS: '/agency/reports',
  AGENCY_USERS: '/agency/users',
  AGENCY_ROLES: '/agency/roles',
  AGENCY_SETTINGS: '/agency/settings',
  AGENCY_PROFILE: '/agency/profile',
  AGENCY_BILLING: '/agency/billing',

  AGENCY_HR_STAFF: '/agency/hr/staff',
  AGENCY_HR_STAFF_DETAIL: '/agency/hr/staff/:id',
  AGENCY_HIRING_PIPELINE: '/agency/hr/hiring-pipeline',
  AGENCY_JOBS: '/agency/hr/jobs',
  AGENCY_JOBS_CREATE: '/agency/hr/jobs/create',
  AGENCY_JOBS_EDIT: '/agency/hr/jobs/:id/edit',
  AGENCY_CANDIDATES: '/agency/hr/candidates',
  AGENCY_CANDIDATE_FORM_PRINT: '/agency/hr/candidates/forms/:applicationId/print/:submissionId',
  AGENCY_INTERVIEW_FEEDBACK_PRINT: '/agency/hr/candidates/interview-feedback/:applicationId/print/:stageId',

  // Public candidate hiring forms
  CANDIDATE_FORM_PORTAL: '/candidate/forms/:token',
  CANDIDATE_FORM_DOCUMENT: '/candidate/forms/:token/:documentCode',

  // Caregiver portal
  CAREGIVER_DASHBOARD: '/caregiver/dashboard',
  CAREGIVER_EVV_ENROLLMENTS: '/caregiver/evv-enrollments',
  CAREGIVER_EVV_ENROLLMENT_FORM: '/caregiver/evv-enrollments/:id',
  CAREGIVER_EVV_ENROLLMENT_PRINT: '/caregiver/evv-enrollments/:id/print',
  CAREGIVER_JOBS: '/caregiver/schedule',
  CAREGIVER_VISITS: '/caregiver/visits',
  CAREGIVER_CLIENTS: '/caregiver/clients',
  CAREGIVER_MESSAGES: '/caregiver/messages',
  CAREGIVER_ALERTS: '/caregiver/alerts',
  CAREGIVER_CLOCK: '/caregiver/clock',
  CAREGIVER_LEAVES: '/caregiver/leaves',
  CAREGIVER_DOCUMENTS: '/caregiver/documents',
  CAREGIVER_SUMMARY: '/caregiver/summary',
  CAREGIVER_PAYMENTS: '/caregiver/payroll',
  CAREGIVER_TRAINING: '/caregiver/training',
  CAREGIVER_SETTINGS: '/caregiver/settings',
  CAREGIVER_PROFILE: '/caregiver/profile',

  // Client portal
  CLIENT_DASHBOARD: '/client/dashboard',
  CLIENT_CARE_PLANS: '/client/care-plans',
  CLIENT_CARE_PLAN_DETAIL: '/client/care-plans/:id',
  CLIENT_CARE_PLANS_PRINT_DRAFT: '/client/care-plans/draft/print',
  CLIENT_SCHEDULE: '/client/schedule',
  CLIENT_CAREGIVERS: '/client/caregivers',
  CLIENT_EVV_VISITS: '/client/evv-visits',
  CLIENT_EVV_ENROLLMENTS: '/client/evv-enrollments',
  CLIENT_EVV_ENROLLMENT_DETAIL: '/client/evv-enrollments/:id',
  CLIENT_MESSAGES: '/client/messages',
  CLIENT_DOCUMENTS: '/client/documents',
  CLIENT_MEDICATIONS: '/client/medications',
  CLIENT_INVOICES: '/client/invoices',
  CLIENT_PROFILE: '/client/profile',
  CLIENT_HELP: '/client/help',

  // Agency registration
  REGISTRATION_ENTRY: '/register',
  REGISTRATION_AGENCY_INFO: '/register/agency-information',
  REGISTRATION_CREATE_ACCOUNT: '/register/create-account',
  REGISTRATION_CONFIRMATION: '/register/confirmation',
};

export { ADMIN_NAV_ITEMS, ADMIN_NAV_GROUPS } from './adminNav';

export const REGISTRATION_STEPS = [
  { key: 'REGISTRATION_AGENCY_INFO', label: 'Agency Information', step: 1 },
  { key: 'REGISTRATION_CREATE_ACCOUNT', label: 'Create Account', step: 2 },
  { key: 'REGISTRATION_CONFIRMATION', label: 'Confirmation', step: 3 },
];
