const API_ROUTES = {
  LOGIN: '/auth/login',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  ME: '/auth/me',
  UPDATE_PROFILE: '/auth/me',
  CHANGE_PASSWORD: '/auth/password',

  ADMIN: {
    AGENCY: {
      LIST: '/admin/agencies',
      CREATE: '/admin/agencies',
      UPDATE: '/admin/agencies',
      DELETE: '/admin/agencies',
    },
    SUBSCRIPTION_PLAN: {
      LIST: '/admin/subscription-plans',
      ACTIVE: '/subscription-plans/active',
      CREATE: '/admin/subscription-plans',
      UPDATE: '/admin/subscription-plans',
      DELETE: '/admin/subscription-plans',
    },
    INVITATION: {
      STATS: '/admin/invitations/stats',
      LIST: '/admin/invitations',
      CREATE: '/admin/invitations',
      RESEND: '/admin/invitations',
      VALIDATE: '/invitations/validate',
    },
  },
  AGENCY: {
    HR_STAFF: {
      STATS: '/agency/hr-staff/stats',
      LIST: '/agency/hr-staff',
      CREATE: '/agency/hr-staff',
      UPDATE: '/agency/hr-staff',
      STATUS: '/agency/hr-staff',
      PASSWORD: '/agency/hr-staff',
      EMAIL: '/agency/hr-staff',
    },
    HIRING_PIPELINE: {
      GET: '/agency/hiring-pipeline',
      DOCUMENTS: '/agency/hiring-pipeline/documents',
      SAVE: '/agency/hiring-pipeline',
      STAGES: '/agency/hiring-pipeline/stages',
    },
    JOBS: {
      LIST: '/agency/jobs',
      CREATE: '/agency/jobs',
      UPDATE: '/agency/jobs',
      DELETE: '/agency/jobs',
      GENERATE_AI: '/agency/jobs/generate-ai',
      COMPLETE_HIRING: '/agency/jobs',
      REOPEN_HIRING: '/agency/jobs',
    },
    JOB_APPLICATIONS: {
      STATS: '/agency/job-applications/stats',
      LIST: '/agency/job-applications',
      CREATE: '/agency/job-applications',
      SET_STAGE: '/agency/job-applications',
      NEXT_STAGE: '/agency/job-applications',
      PREVIOUS_STAGE: '/agency/job-applications',
      REJECT: '/agency/job-applications',
      UNDO_HIRE: '/agency/job-applications',
      COMPLETE_HIRE: '/agency/job-applications',
      HIRED: '/agency/job-applications/hired',
      REJECTED: '/agency/job-applications/job',
      BY_STAGE: '/agency/job-applications/job',
      FORM_SUBMISSIONS: '/agency/job-applications',
      FORM_PRINT: '/agency/job-applications',
      RESEND_FORM_EMAIL: '/agency/job-applications',
      RESET_FORM: '/agency/job-applications',
      INTERVIEW_FEEDBACK: '/agency/job-applications',
      EMAIL: '/agency/job-applications',
    },
    INTERVIEW_FEEDBACK: {
      OPTIONS: '/agency/interview-feedback/options',
    },
    CAREGIVERS: {
      STATS: '/agency/caregivers/stats',
      LIST: '/agency/caregivers',
    },
    CLIENTS: {
      OPTIONS: '/agency/clients/options',
      STATS: '/agency/clients/stats',
      LIST: '/agency/clients',
    },
    ASSESSMENTS: {
      OPTIONS: '/agency/assessments/options',
      STATS: '/agency/assessments/stats',
      LIST: '/agency/assessments',
    },
    CARE_PLANS: {
      OPTIONS: '/agency/care-plans/options',
      STATS: '/agency/care-plans/stats',
      LIST: '/agency/care-plans',
    },
    INSURANCE_INTAKES: {
      OPTIONS: '/agency/insurance-intakes/options',
      STATS: '/agency/insurance-intakes/stats',
      LIST: '/agency/insurance-intakes',
    },
    EVV_ENROLLMENTS: {
      OPTIONS: '/agency/evv-enrollments/options',
      STATS: '/agency/evv-enrollments/stats',
      LIST: '/agency/evv-enrollments',
      SYNC: '/agency/evv-enrollments/sync',
    },
    VISIT_SCHEDULES: {
      OPTIONS: '/agency/visit-schedules/options',
      STATS: '/agency/visit-schedules/stats',
      LIST: '/agency/visit-schedules',
      CARE_PLAN_SOURCES: '/agency/visit-schedules/care-plan',
    },
    VISITS: {
      LIST: '/agency/visits',
      APPROVE: '/agency/visits',
      REJECT: '/agency/visits',
      RESOLVE_EXCEPTION: '/agency/visits',
    },
    EVV_DASHBOARD: '/agency/evv/dashboard',
    EVV_SETTINGS: '/agency/evv/settings',
    INVOICES: {
      LIST: '/agency/invoices',
      GENERATE: '/agency/invoices/generate',
      SEND: '/agency/invoices',
      PAID: '/agency/invoices',
      VOID: '/agency/invoices',
    },
  },
  CAREGIVER: {
    DASHBOARD: '/caregiver/dashboard',
    EVV_ENROLLMENTS: {
      LIST: '/caregiver/evv-enrollments',
      SUBMIT: '/caregiver/evv-enrollments',
    },
    VISITS: {
      LIST: '/caregiver/visits',
      ACTIVE: '/caregiver/visits/active',
      TIMER: '/caregiver/visits',
      CHECK_IN: '/caregiver/visits',
      CHECK_OUT: '/caregiver/visits',
    },
  },
  REGISTRATION: {
    CHECK_USER_ID: '/registration/check-user-id',
    ACCOUNT: '/registration/account',
    SUBMIT: '/registration/submit',
    PAYMENT: '/registration/payment',
  },
  CANDIDATE_FORMS: {
    PORTAL: '/candidate-forms',
  },
};

export default API_ROUTES;
